server:
  port: 8080
  servlet:
    context-path: /html

---

spring:
  profiles: default

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8087

---

spring:
  profiles: docker
