apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
  labels:
    app: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
        - name: html
          image: jihwancha/mybnb-html:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/html/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/html/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5