apiVersion: apps/v1
kind: Deployment
metadata:
  name: commission
  labels:
    app: commission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commission
  template:
    metadata:
      labels:
        app: commission
    spec:
      containers:
        - name: commission
          image: username/commission:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5